[package]
name = "factories"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
fs-err = "3.1.0"
itertools = "0.14.0"
nalgebra = "0.33.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.8.22"
